name: Lint Python Scripts

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you want to use

    - name: Install linter
      run: pip install pylint

    - name: Lint spring_constant_unittest.py
      run: pylint spring_constant_unittest.py

    - name: Lint spring_const_graph.py
      run: pylint spring_const_graph.py
